// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list_recent_leads.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/tools/_supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.105.1";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  if (!url || !key) throw new Error("Supabase env not configured");
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function currentClientId(ctx) {
  const sb = supabaseForUser(ctx);
  const userId = ctx.getUserId();
  const email = ctx.getUserEmail();
  const { data } = await sb.from("callcapture_clients").select("id").eq("user_id", userId).order("created_at", { ascending: false }).limit(1).maybeSingle();
  if (data?.id) return data.id;
  if (email) {
    const { data: byEmail } = await sb.from("callcapture_clients").select("id").ilike("email", email).order("created_at", { ascending: false }).limit(1).maybeSingle();
    return byEmail?.id ?? null;
  }
  return null;
}

// src/lib/mcp/tools/list_recent_leads.ts
var list_recent_leads_default = defineTool({
  name: "list_recent_leads",
  title: "List recent leads",
  description: "List the signed-in Vektuor account's most recent captured leads (name, phone, issue, status, created_at).",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("How many leads to return (max 50)."),
    status: z.string().optional().describe("Optional status filter, e.g. 'new', 'booked'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const clientId = await currentClientId(ctx);
    if (!clientId) return { content: [{ type: "text", text: "No Vektuor client found for this user." }], isError: true };
    const sb = supabaseForUser(ctx);
    let q = sb.from("callcapture_leads").select("id, name, phone, email, issue, summary, status, urgency, created_at").eq("client_id", clientId).order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { leads: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get_lead.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_lead_default = defineTool2({
  name: "get_lead",
  title: "Get lead",
  description: "Get the full details for a single lead by id, including transcript and intake answers.",
  inputSchema: {
    lead_id: z2.string().uuid().describe("The lead's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lead_id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const clientId = await currentClientId(ctx);
    if (!clientId) return { content: [{ type: "text", text: "No Vektuor client found for this user." }], isError: true };
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("callcapture_leads").select("*").eq("id", lead_id).eq("client_id", clientId).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Lead not found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/list_recent_calls.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_recent_calls_default = defineTool3({
  name: "list_recent_calls",
  title: "List recent calls",
  description: "List the signed-in account's most recent AI receptionist calls with basic metadata.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(10).describe("How many calls to return (max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const clientId = await currentClientId(ctx);
    if (!clientId) return { content: [{ type: "text", text: "No Vektuor client found for this user." }], isError: true };
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("callcapture_calls").select("*").eq("client_id", clientId).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { calls: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get_business_profile.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_business_profile_default = defineTool4({
  name: "get_business_profile",
  title: "Get business profile",
  description: "Return the signed-in Vektuor account's business profile, hours, AI greeting, tone, and assigned phone number.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated." }], isError: true };
    const clientId = await currentClientId(ctx);
    if (!clientId) return { content: [{ type: "text", text: "No Vektuor client found for this user." }], isError: true };
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("callcapture_clients").select("id, business_name, business_email, business_phone, address, website, industry, tone, greeting, voice_label, assigned_callcapture_number, business_hours_schedule, business_hours_24_7, services, service_area").eq("id", clientId).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mzqazxtcwqumroqtmtjd";
var mcp_default = defineMcp({
  name: "vektuor-mcp",
  title: "Vektuor",
  version: "0.1.0",
  instructions: "Tools for the Vektuor AI receptionist. Use `list_recent_leads` and `get_lead` to review captured leads, `list_recent_calls` for call history, and `get_business_profile` for the account's setup (hours, greeting, phone number).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_recent_leads_default, get_lead_default, list_recent_calls_default, get_business_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
