
ALTER TABLE public.callcapture_clients
  ADD COLUMN IF NOT EXISTS business_category_group text,
  ADD COLUMN IF NOT EXISTS business_email text,
  ADD COLUMN IF NOT EXISTS service_area jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS emergency_services boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS emergency_rules jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS holiday_hours jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS language text DEFAULT 'en-US',
  ADD COLUMN IF NOT EXISTS conversation_style text,
  ADD COLUMN IF NOT EXISTS ai_personality text,
  ADD COLUMN IF NOT EXISTS transfer_number text,
  ADD COLUMN IF NOT EXISTS voicemail_enabled boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS call_recording_enabled boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS call_summary_enabled boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS sms_followup_enabled boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS scheduling_enabled boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS scheduling_mode text DEFAULT 'intake_only',
  ADD COLUMN IF NOT EXISTS diagnostic_fee numeric,
  ADD COLUMN IF NOT EXISTS company_policies text,
  ADD COLUMN IF NOT EXISTS warranty_terms text,
  ADD COLUMN IF NOT EXISTS brands_serviced text[] DEFAULT ARRAY[]::text[],
  ADD COLUMN IF NOT EXISTS service_area_notes text,
  ADD COLUMN IF NOT EXISTS knowledge_base text,
  ADD COLUMN IF NOT EXISTS webhook_urls jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS webhook_secret text,
  ADD COLUMN IF NOT EXISTS industry_workflow jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS last_vapi_sync_at timestamptz,
  ADD COLUMN IF NOT EXISTS last_vapi_sync_status text;
